version: '3.4'
volumes:
  dbvolume:

services:
  db:
    image: mysql:5.7.22
    volumes:
    - dbvolume:/var/lib/mysql
    command: mysqld --default_authentication_plugin=mysql_native_password
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: financeiro
    ports:
      - 3308:3306
    networks:
      - rede
  api:
    build:
      context: .
    environment:
      TZ: America/Sao_Paulo
      spring.datasource.url: jdbc:mysql://db:3306/financeiro?createDatabaseIfNotExist=true&&useSSL=false&&useTimezone=true&&serverTimezone=UTC
      flyway.url: jdbc:mysql://db:3306
      spring.datasource.username: root
      spring.datasource.password: root
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - rede
networks:
  rede:
    driver: bridge